# Generated by Django 4.2 on 2025-01-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rental_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_collection_time', models.DateField()),
                ('status', models.CharField(choices=[('active', '有效'), ('terminated', '终止'), ('expired', '过期')], default='active', max_length=20)),
                ('current_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('deposit', '保证金'), ('rent', '租金'), ('management_fee', '物业管理费')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term', models.CharField(max_length=50)),
                ('is_collected', models.BooleanField(default=False)),
                ('overdue_status', models.CharField(choices=[('on_time', '按时'), ('overdue', '逾期')], default='on_time', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('POS', 'POS'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank_transfer', '银行转账'), ('other', '其他')], max_length=20, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('bank_slip', models.FileField(blank=True, null=True, upload_to='bank_slips/')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='rental_app.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=20, unique=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('rental_status', models.CharField(choices=[('rented', '已租赁'), ('available', '未租赁'), ('maintenance', '维护中')], default='available', max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maintenance_status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('POS', 'POS'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank_transfer', '银行转账'), ('other', '其他')], max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental_app.fee')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='properties',
            field=models.ManyToManyField(related_name='contracts', to='rental_app.property'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rental_app.tenant'),
        ),
    ]
