# Generated by Django 4.2 on 2025-01-17 09:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='经营业态'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='合同文件'),
        ),
        migrations.AddField(
            model_name='contract',
            name='decoration_period',
            field=models.IntegerField(default=0, verbose_name='装修期(天)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='保证金'),
        ),
        migrations.AddField(
            model_name='contract',
            name='management_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='物业管理费'),
        ),
        migrations.AddField(
            model_name='contract',
            name='promotion_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='推广费'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rent_free_period',
            field=models.IntegerField(default=0, verbose_name='免租期(天)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rental_purpose',
            field=models.TextField(blank=True, null=True, verbose_name='租赁用途'),
        ),
        migrations.AddField(
            model_name='contract',
            name='utilities_payment',
            field=models.TextField(blank=True, null=True, verbose_name='水电费支付方式'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='current_outstanding',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='current_receivable',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_overdue',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
